In [ ]:
import numpy as np

### 색인

In [7]:
arr=np.arange(10)
print("arr:",arr)
print("arr[5]:",arr[5])
print("arr[5:8]:",arr[5:8])

arr: [0 1 2 3 4 5 6 7 8 9]
arr[5]: 5
arr[5:8]: [5 6 7]


In [9]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

### 슬라이싱

In [10]:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

arr_slice값을 변경하면 원래 배열인 arr의 값도 바뀐다

In [11]:
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [12]:
# [:]를 통한 배열의 모든 값을 할당
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

#### 2차원 배열에서 각 색인에 해당하는 요소는 스칼라값이 아니라 1차원 배열이다

In [14]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

#### 개별요소는 재귀적으로 접근해야한다. 하지만 귀찮아서 콤마로 구분된 색인 리스트 사용

In [15]:
print(arr2d[0][2])
print(arr2d[0,2])

3
3


#### 3d

In [16]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
#arr3d에는 스칼라 값과 배열 모두 대입할 수 있다.
old_values=arr3d[0].copy
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
# arr3d[1,0]은(1,0)으로 색인되는 1차원 배열과 그 값을 반환
arr3d[1,0]

array([7, 8, 9])

### 슬라이스로 선택하기

In [21]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

### 2차원 슬라이싱

In [33]:
#arr2d의 case
print("arr2d:\n", arr2d)
print("arr2d[:2]:\n", arr2d[:2])
print("arr2d[:2,1:]:\n",arr2d[:2,1:])
print("arr2d[1,:2]:\n",arr2d[1,:2])
print("arr2d[:2,2]:\n",arr2d[:2,2])
print("arr2d[:,.:1]:\n",arr2d[:,:1])

arr2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[:2]:
 [[1 2 3]
 [4 5 6]]
arr2d[:2,1:]:
 [[2 3]
 [5 6]]
arr2d[1,:2]:
 [4 5]
arr2d[:2,2]:
 [3 6]
arr2d[:,.:1]:
 [[1]
 [4]
 [7]]


In [34]:
arr2d[:2,1:]=0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])