### reshape을 통한 배열 변환

In [2]:
import numpy as np
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### T를 통한 전치

In [3]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#### np.dot

In [5]:
arr=np.random.randn(6,3)
arr

array([[-0.55451229, -0.15636389,  0.08724978],
       [-0.29144119,  0.1351217 , -2.21962808],
       [-1.19360218, -0.06843437,  0.69447057],
       [ 0.98986634, -2.22737989, -2.58735714],
       [ 0.27828758, -0.46377769, -0.18483295],
       [ 1.14053378,  0.6411855 , -0.83122901]])

In [6]:
np.dot(arr.T,arr)

array([[ 4.17520467, -1.47356913, -3.79103083],
       [-1.47356913,  5.63482059,  4.95468837],
       [-3.79103083,  4.95468837, 12.83617257]])

### 다차원 배열의 경우transpose메서드는 튜플로 축 번호를 받아서 치환한다.

In [7]:
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [8]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])