In [1]:
#중복된 이름이 포함된 배열이 있다고 하자. 그리고 numpy.ranfom모듈에 있는 
#randn함수를 사용해서 임의의 표준정규분포 데이터를 생성하자

In [5]:
import numpy as np
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4) #7*4 랜덤행렬 생성
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [6]:
data

array([[-0.92146629,  1.03544315,  0.16093005, -1.06492135],
       [-0.94731057, -1.42438717,  0.45182162, -0.78828992],
       [ 0.46794321, -0.13591298, -1.26377478, -1.26129042],
       [ 0.78120415, -0.46670429,  1.30260084,  1.09039892],
       [-0.53315851, -0.46454631, -0.32266546,  0.71082127],
       [ 0.54189486,  0.3148036 , -0.98747236,  1.1997909 ],
       [-1.6161956 ,  0.01577978, -0.49882133,  0.9712764 ]])

In [7]:
# 각각의 이름은 data배열의 각 로우에 대응한다고 가정하자. 만약 Bob과 같은 이름을 선택하려면 비교연산 사용(==)
names=='Bob'


array([ True, False, False,  True, False, False, False])

In [9]:
#불린 인덱싱은 색인으로 사용할 수도 있다.
#불린배열은 반드시 색인하려는 축의 길이와 동일한 길이를 가져야한다.
#불린 배열의 크기가 다르더라도 실패하지 않기 에 주의해야함
data[names=='Bob']

array([[-0.92146629,  1.03544315,  0.16093005, -1.06492135],
       [ 0.78120415, -0.46670429,  1.30260084,  1.09039892]])

In [11]:
# 불린 인덱싱으로 row  &column선택
data[names=='Bob',2:]


array([[ 0.16093005, -1.06492135],
       [ 1.30260084,  1.09039892]])

In [12]:
data[names=='Bob',3]

array([-1.06492135,  1.09039892])

In [13]:
# !,~를 사용해서 조건절을 부인할 수 있다,
names !='Bob'

array([False,  True,  True, False,  True,  True,  True])

In [14]:
data[~(names=='Bob')]

array([[-0.94731057, -1.42438717,  0.45182162, -0.78828992],
       [ 0.46794321, -0.13591298, -1.26377478, -1.26129042],
       [-0.53315851, -0.46454631, -0.32266546,  0.71082127],
       [ 0.54189486,  0.3148036 , -0.98747236,  1.1997909 ],
       [-1.6161956 ,  0.01577978, -0.49882133,  0.9712764 ]])

In [15]:
# ~연산자는 일반적인 조건을 반대로 쓰고 싶을 때 유용
cond=names=='Bob'
data[~cond]

array([[-0.94731057, -1.42438717,  0.45182162, -0.78828992],
       [ 0.46794321, -0.13591298, -1.26377478, -1.26129042],
       [-0.53315851, -0.46454631, -0.32266546,  0.71082127],
       [ 0.54189486,  0.3148036 , -0.98747236,  1.1997909 ],
       [-1.6161956 ,  0.01577978, -0.49882133,  0.9712764 ]])

In [16]:
# or&and기능을 통한 불린 조건
mask=(names=='Bob')|(names=='Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [17]:
data[mask]

array([[-0.92146629,  1.03544315,  0.16093005, -1.06492135],
       [ 0.46794321, -0.13591298, -1.26377478, -1.26129042],
       [ 0.78120415, -0.46670429,  1.30260084,  1.09039892],
       [-0.53315851, -0.46454631, -0.32266546,  0.71082127]])

### 불린 인덱싱을 활용한 값 대입 !!!!!!!!!

In [19]:
#0보다 작은 수를 0으로 대체
data[data<0]=0
data

array([[0.        , 1.03544315, 0.16093005, 0.        ],
       [0.        , 0.        , 0.45182162, 0.        ],
       [0.46794321, 0.        , 0.        , 0.        ],
       [0.78120415, 0.        , 1.30260084, 1.09039892],
       [0.        , 0.        , 0.        , 0.71082127],
       [0.54189486, 0.3148036 , 0.        , 1.1997909 ],
       [0.        , 0.01577978, 0.        , 0.9712764 ]])

In [20]:
data[names != 'Joe']=7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.45182162, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.54189486, 0.3148036 , 0.        , 1.1997909 ],
       [0.        , 0.01577978, 0.        , 0.9712764 ]])