In [1]:
import numpy as np
data=np.random.randn(2,3)

data

array([[-0.64166501, -0.85106904, -1.37016616],
       [ 0.30391126, -0.11355915, -1.30458559]])

### 연산

In [2]:
data*10

array([[ -6.4166501 ,  -8.51069039, -13.70166159],
       [  3.03911263,  -1.13559145, -13.04585594]])

In [3]:
data+data

array([[-1.28333002, -1.70213808, -2.74033232],
       [ 0.60782253, -0.22711829, -2.60917119]])

## ndarray는 같은 종류의 데이터를 담을 수 있는 포괄적인 다차원 배열이다. ndarray의 모든 원소는 같은 자료형이어야 한다.


## 모든 배열은 shape&dtype을 가진다

In [4]:
print(data.shape)
print(data.dtype)

(2, 3)
float64
