In [1]:
import numpy as np

arr=np.empty((8,4))
#4짜리 빈 list를 8개 생성

for i in range(8):
    arr[i]=i

arr


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [3]:
# 원하는 열을 원하는 순서로 뽑기
arr[[4,3,0,6]]


array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [4]:
#색인으로 음수를 사용하면 끝에서부터 로우를 선택한다.
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [5]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [6]:
# 다차원 (1,0)(5,3)(7,1)(2,2)
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])