dtype은 ndarray가 메모리에 있는 특정 데이터를 해석하기 위해 필요한 정보(또는 메타데이터)를 담고 있는 특수한 객체이다.

In [1]:
import numpy as np

In [3]:
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


### ndarray의 astype메서드를 사용해서 배열의 dtype을 다른 형으로 명시적으로 변환(캐스팅) 가능하다.


In [4]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [5]:
float_arr=arr.astype(np.float64)
print(float_arr.dtype)

float64


부동소수점수->정수형: 소수점 아래 자리는 버려진다

In [6]:
arr=np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [7]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

#### 숫자 형식의 문자열을 담고 있는 배열이 있다면 astype을 사용하여 숫자로 변환할 수 있다.

In [8]:
numeric_strings=np.array(['1.25','-9.6','42'],dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

#### 다른배열의 dtype 속성을 이용하는 것도 가능

In [10]:
int_array=np.arange(10)
calibers=np.array([.22,.27],dtype=np.float64)

int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])