### 배열을 생성하는 가장 쉬운 방법은 array함수를 이용하는 것이다.


In [2]:
import numpy as np

data1=[6,7.5,8,0,1]
arr1=np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
#리스트 내포 다차원 배열로 변환
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

ndim, shape, dtype 속성을 검사

In [5]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

2
(2, 4)
int32


zeros, ones 를 활용한 새로운 배열 형성

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

arange:파이선의 range함수의 배열버전

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### np는 산술 연산에 초점이 맞춰져 있기 때문에 만약 자료형을 명시하지 않으면 float64형이 된다