### 배열의 중요한 특징은 for문을 작성하지 않고 데이터를 일관 처리할 수 있다는 것이다.

## 이를 벡터화라고 한다

In [2]:
import numpy as np

In [3]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
#위치가 맞는 원소별로 곱함 (합과 같은 형식)
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [8]:
# 위치가 맞는 원소별로 뺄셈
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#스칼라 연산
#  *은 곱하기,  **은 루트
print(1/arr)
print(arr**0.5)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [13]:
# 같은 크기를 가지는 배열 간의 비교 연산은 불리언(불린) 배열을 반환한다.
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])

arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

#### 크기가 다른 배열 간의 연산은 broadcasting(브로드캐스팅)이라고 한다